all_for_kids_liver_homepage:
    path:     /
    defaults: { _controller: AllForKidsLiverBundle:Default:index }
AffichLiver:
    path:     /AfficheLivre
    defaults: { _controller: AllForKidsLiverBundle:Liver:ShowAll }
AjoutLiver:
    path:     /admin/AjoutLivre
    defaults: { _controller: AllForKidsLiverBundle:Liver:Add }
DetailLiver :
    path:     /DetailLiver{id}
    defaults: { _controller: AllForKidsLiverBundle:Liver:Show }
RechercheLiver :
    path:     /RechercheLiver
    defaults: { _controller: AllForKidsLiverBundle:Liver:SearchDQLCategori }