transport_transport:
    resource: "@TransportBundle/Resources/config/routing/transport.yml"
    prefix:   /transport

template_homepage:
    path:     /home
    defaults: { _controller: TransportBundle:Default:index }

map:
    path:     /map
    defaults: { _controller: TransportBundle:Default:map }

login:
    path:     /login
    defaults: { _controller: TransportBundle:Security:login }

logout:
    path:     /logout
    defaults: { _controller: TransportBundle:Security:logout }
