all_for_kids_divertissement_homepage:
    path:     /
    defaults: { _controller: AllForKidsDivertissementBundle:Default:index }
afficheE:
    path:     /admin/Afficheev
    defaults: { _controller: AllForKidsDivertissementBundle:Evenement:ShowAll }
AjoutE:
    path:     /Ajoutev
    defaults: { _controller: AllForKidsDivertissementBundle:Evenement:Add }
DetailE:
    path:     /Detailev{id}
    defaults: { _controller: AllForKidsDivertissementBundle:Evenement:Show }
ParticipE:
    path:     /participev{id}
    defaults: { _controller: AllForKidsDivertissementBundle:Evenement:Particip }
AnulParticipE:
    path:     /Anulparticipev{id}
    defaults: { _controller: AllForKidsDivertissementBundle:Evenement:AnulParticip }
MyEvent:
    path:     /MyEvent
    defaults: { _controller: AllForKidsDivertissementBundle:Evenement:MyEvent }
SemainEvent:
    path:     /SemainEvent
    defaults: { _controller: AllForKidsDivertissementBundle:Evenement:SemainEvent }
MesEventInsc:
    path:     /MesEvent
    defaults: { _controller: AllForKidsDivertissementBundle:Evenement:MesEventInsc }
Recherche:
    path:     /Recherche{nom}
    defaults: { _controller: AllForKidsDivertissementBundle:Evenement:Recherch }
Delete:
    path:     /delete{id}
    defaults: { _controller: AllForKidsDivertissementBundle:Evenement:Delete }
Update:
    path:     /modifier{id}
    defaults: { _controller: AllForKidsDivertissementBundle:Evenement:Update }
DeleteD:
    path:     /DeleteD
    defaults: { _controller: AllForKidsDivertissementBundle:Evenement:SupprimerD }
ajax_star_rating_system:
  path:  /ajax/starrating/update/data
  defaults: { _controller: AllForKidsDivertissementBundle:AjaxStarratingsystem:updateData }