services:
#    all_for_kids_divertissement.example:
#        class: AllForKids\DivertissementBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
 all_for_kids_divertissement.twig_extension:
        class: AllForKids\DivertissementBundle\Twig\StarRatingExtension
        arguments: ["@doctrine"]
        tags:
            - { name : twig.extension }