all_for_kids_entity_homepage:
    path:     /
    defaults: { _controller: AllForKidsEntityBundle:Default:index }



user:
    path:     /by/{userName}
    defaults: { _controller: AllForKidsEntityBundle:Default:FindByLogin }

Inscrit:
    path:     /Inscrit/{username}/{nom}/{prenom}/{role}/{email}/{cin}/{password}/{date}/{photo}
    defaults: { _controller: AllForKidsEntityBundle:Default:Inscrit }




Modifier:
    path:     /Modifier/{id}/{username}/{nom}/{prenom}/{role}/{email}/{cin}/{password}/{date}/{photo}
    defaults: { _controller: AllForKidsEntityBundle:Default:Modifier }