<?php

namespace EtablissementBundle\Repository;

/**
 * RejoindreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RejoindreRepository extends \Doctrine\ORM\EntityRepository
{
}
