etablissement_etablissement:
    resource: "@EtablissementBundle/Resources/config/routing/etablissement.yml"
    prefix:   /etablissement

liste_eleves:
    path:     /liste_eleves/{idetab}
    defaults: { _controller: EtablissementBundle:Default:eleves }
moyenne:
    path:     /moyenne/
    defaults: { _controller: EtablissementBundle:Default:moyenne }
eleve_note:
    path:     /noter_eleve/{idelev}
    defaults: { _controller: EtablissementBundle:Default:note }

eleve_valide:
    path:     /valid/{id}
    defaults: { _controller: EtablissementBundle:Default:elevesval }

etablissement_homepage:
    path:     /
    defaults: { _controller: EtablissementBundle:Default:index }

etablissement_valide:
    path:     /valider/{idetab}
    defaults: { _controller: EtablissementBundle:Etablissement:valider }

etablissement_info:
    path:     /inf
    defaults: { _controller: EtablissementBundle:Etablissement:info }

etablissement_rejoinde:
    path:     /rej/{idetab}
    defaults: { _controller: EtablissementBundle:Etablissement:rejoindre }

all1:
    path:     /all1
    defaults: { _controller: EtablissementBundle:Default:all1 }

find1:
    path:     /find1/{id}
    defaults: { _controller: EtablissementBundle:Default:find1 }

new1:
    path:     /new1/{user}/{nom}/{type}/{region}/{ville}/{description}/{image}/{verification}
    defaults: { _controller: EtablissementBundle:Default:new1 }

allregion:
    path:     /allregion
    defaults: { _controller: EtablissementBundle:Default:allregion }

findville:
    path:     /findville/{id}
    defaults: { _controller: EtablissementBundle:Default:findville }


findidregion:
    path:     /findidregion/{nom}
    defaults: { _controller: EtablissementBundle:Default:findidregion }


delete:
    path:     /delete/{id}
    defaults: { _controller: EtablissementBundle:Default:delete }


