<?php

namespace MedBundle\Repository;

/**
 * essageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class essageRepository extends \Doctrine\ORM\EntityRepository
{
}
